[package]
name = "serde-saphyr"
version = "0.0.3"
edition = "2024"
license = "MIT"
description = "YAML deserializer for Serde, built on top of Saphyr, emphasizing panic-free parsing."
documentation = "https://docs.rs/serde-saphyr/latest/serde-saphyr/"
repository = "https://github.com/bourumir-wyngs/serde-saphyr"
readme = "README.md"
categories = ["encoding", "parser-implementations", "config"]
keywords = ["yaml", "serde", "serialization", "deserialization", "config"]

[dependencies]
saphyr-parser = "0.0.6"
serde = { version = "1", features = ["derive"] }
# Our all tests are fine with alpha.
smallvec = "2.0.0-alpha.11"
