[package]
name = "serde-saphyr"
version = "0.0.1"

authors = ["Bourumir Wyngs <bourumir.wyngs@gmail.com>"]
categories = ["encoding", "parser-implementations"]
description = "YAML deserializer for Serde with an emphasis on panic-free parsing on the top of Saphyr."
documentation = "https://docs.rs/serde_yaml_bw/latest/serde_yaml_bw/"
edition = "2024"
keywords = ["yaml", "serde", "serialization"]
license = "MIT"

[dependencies]
saphyr-parser = "0.0.6"
serde = { version = "1", features = ["derive", "alloc", "rc"] }

